using System;
using System.Collections.Generic;
using System.Text;

namespace NexusFlow.AppCore.DTOs.Sales
{
    public class SalesOrderDto
    {
        public int Id { get; set; }

        // Auto-generated by the system, but useful when returning the DTO to the UI
        public string OrderNumber { get; set; } = string.Empty;

        public DateTime OrderDate { get; set; }

        // Master Data Links
        public int CustomerId { get; set; }
        public string? CustomerName { get; set; } // For Grid/UI display

        public int SalesRepId { get; set; }
        public string? SalesRepName { get; set; } // For Grid/UI display

        // State Control
        // If true, status becomes Draft. If false, status becomes Submitted.
        public bool IsDraft { get; set; }
        public string? StatusText { get; set; } // e.g., "Draft", "Submitted", "Converted"

        public string Notes { get; set; } = string.Empty;

        // Calculated Totals (Sent back to UI, but backend always recalculates for security)
        public decimal TotalAmount { get; set; }

        // Line Items
        public List<SalesOrderItemDto> Items { get; set; } = new();
    }

    public class SalesOrderItemDto
    {
        public int Id { get; set; }

        public int ProductVariantId { get; set; }

        // Useful for displaying the order back to the user
        public string? ProductName { get; set; }
        public string? SKU { get; set; }

        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }

        // Discount applied specifically to this line
        public decimal Discount { get; set; }

        // LineTotal = (Quantity * UnitPrice) - Discount
        public decimal LineTotal { get; set; }
    }
}
